import { Activity, Lock, Timer, Zap } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { getLogs, getToday, saveSet } from './api';
import { useWorkoutStore } from './store/workoutStore';

function formatTime(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`; }

export function App() {
  const [weightKg, setWeightKg] = useState(''); const [reps, setReps] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const store = useWorkoutStore(); const exercise = store.getCurrentExercise(); const previousSet = store.getPreviousSet();
  useEffect(() => { void (async () => { try { const today = await getToday(); const logs = await getLogs(today.cycleDate); store.setWorkout(today.cycleDay, today.cycleDate, today.day, logs.logs); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to initialize workout.'); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { if (!store.timerActive || store.timerPaused) return; const id = window.setInterval(() => store.tickTimer(), 1000); return () => window.clearInterval(id); }, [store.timerActive, store.timerPaused, store.tickTimer]);
  const days = useMemo(() => Array.from({ length: 7 }, (_, i) => i + 1), []);
  async function onSubmit(event: FormEvent) { event.preventDefault(); if (!exercise || !weightKg || !reps) return; setError(''); try { const result = await saveSet({ exerciseId: exercise.id, cycleDay: store.cycleDay, cycleDate: store.cycleDate, setNumber: store.setNumber, weightKg: Number(weightKg), reps: Number(reps) }); store.addLog(result.log); setWeightKg(''); setReps(''); if (result.restSeconds > 0) store.startTimer(result.restSeconds); else store.advance(); } catch (err) { setError(err instanceof Error ? err.message : 'Set could not be saved.'); } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-obsidian text-volt font-mono">Loading metamorphosis...</main>;
  if (store.timerActive) return <main className="min-h-screen bg-obsidian text-white p-6 flex flex-col items-center justify-center text-center"><Timer className="text-volt mb-6" size={48}/><p className="uppercase tracking-[0.4em] text-steel text-xs mb-3">Active recovery</p><h1 className="font-mono text-7xl text-volt mb-8">{formatTime(store.timerSeconds)}</h1><div className="grid grid-cols-3 gap-3 w-full max-w-md mb-4">{[10,15,20].map((s)=><button key={s} className="btn-secondary" onClick={()=>store.addTimerSeconds(s)}>+{s}s</button>)}</div><div className="grid grid-cols-2 gap-3 w-full max-w-md"><button className="btn-primary" onClick={store.togglePause}>{store.timerPaused ? 'Resume' : 'Pause'}</button><button className="btn-secondary" onClick={store.skipTimer}>Skip Rest</button></div></main>;
  return <main className="min-h-screen bg-obsidian text-white p-4 sm:p-8"><section className="mx-auto max-w-2xl"><header className="mb-6 border border-charcoal bg-carbon p-5 rounded"><div className="flex items-center gap-2 text-volt font-mono uppercase tracking-[0.3em] text-xs"><Zap size={16}/> The Butterfly Project</div><h1 className="mt-4 text-3xl font-extrabold">{store.day?.name ?? 'Training day'}</h1><p className="text-steel mt-2">Cycle day {store.cycleDay} - {store.cycleDate}</p><div className="grid grid-cols-7 gap-2 mt-5">{days.map((day)=>{ const locked = day > store.cycleDay; return <div key={day} className={`h-10 grid place-items-center rounded border font-mono ${locked ? 'border-charcoal text-steel/40' : day === store.cycleDay ? 'border-volt text-volt' : 'border-charcoal text-steel'}`}>{locked ? <Lock size={14}/> : day}</div>; })}</div></header>{error && <p className="mb-4 border border-red-500/40 bg-red-950/40 p-3 text-red-200 rounded">{error}</p>}{store.day?.exercises.length === 0 || store.completed ? <section className="border border-charcoal bg-graphite p-6 rounded text-center"><Activity className="mx-auto text-volt mb-4" size={42}/><h2 className="text-2xl font-bold">Day complete</h2><p className="text-steel mt-3">Consume <strong className="text-volt">160g-175g protein</strong> to grow from 77.78 kg to 83.0 kg. No atajos: consistencia, comida y registro.</p></section> : exercise && <section className="border border-charcoal bg-graphite p-5 rounded"><p className="text-steel uppercase tracking-[0.25em] text-xs">Current exercise - Set {store.setNumber}/{exercise.sets}</p><h2 className="font-mono text-3xl text-volt mt-3">{exercise.name}</h2><div className="grid grid-cols-2 gap-3 mt-5 text-sm"><div className="metric"><span>Target</span><strong>{exercise.targetReps}</strong></div><div className="metric"><span>RPE</span><strong>{exercise.rpe}</strong></div><div className="metric col-span-2"><span>Breath</span><strong>{exercise.breath}</strong></div></div>{exercise.warmup && <p className="mt-4 text-volt text-sm">Warmup marker active.</p>}{previousSet && <div className="mt-5 border border-volt/30 bg-volt/10 p-3 rounded text-sm">Ghost set: {previousSet.weightKg} kg x {previousSet.reps} reps</div>}<form onSubmit={onSubmit} className="mt-6 grid gap-4"><label className="field">Weight kg<input value={weightKg} onChange={(e)=>setWeightKg(e.target.value)} inputMode="decimal" type="number" min="0" step="0.25" required /></label><label className="field">Reps<input value={reps} onChange={(e)=>setReps(e.target.value)} inputMode="numeric" type="number" min="1" step="1" required /></label><button className="btn-primary disabled:opacity-40" disabled={!weightKg || !reps}>Save set</button></form></section>}</section></main>;
}

